spring:
  application:
    name: ${AUTH_APP_NAME:auth-service}
  datasource:
    url: ${AUTH_URL_MYSQL:jdbc:mysql://18.175.139.240:3306/auth_service}
    username: ${AUTH_USERNAME_MYSQL:diemdk}
    password: ${AUTH_PASSWORD_MYSQL:12345678}
    driverClassName: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true
  eureka:
    client:
      service-url:
        defaultZone: ${AUTH_URL_DEFAULT:http://discovery-server-container:8100/eureka/}
      enabled: ${AUTH_ENABLED:true}

server:
  port: ${AUTH_SERVER_PORT:8102}

jwtExpiration: ${AUTH_JWT_EXPIRATION:120}

management:
  endpoints:
    web:
      exposure:
        include: "*"
